name: "Deploy to NuGet"

on:
#  push: 
   
 #   tags:
  #   - 'v*'
  workflow_dispatch:
  

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
      - name: build, pack & publish
        uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
        
        
          PACKAGE_NAME: Harrydummytest2022.nupkg
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
