name: Publish NuGet

on:
#  push: 
   
 #   tags:
  #   - 'v*'
  workflow_dispatch:
  

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
      - name: build, pack & publish
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 3.1.200
      - name: Authenticating githubtoken
        run: dotnet nuget add source --username Himanshu-Parihar --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Himanshu-Parihar/index.json"
      - name: Publish the package with PAT
        run: dotnet nuget push .\Harrydummytest2022.nupkg  --api-key Nuget_PUBLISH --source "github"
      
      # Publish
     # - name: publish on version change
     #   id: publish_nuget
     ##   uses: brandedoutcast/publish-nuget@v2
      #  with:
        
        
       #   PACKAGE_NAME: Harrydummytest2022.nupkg
        #  NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         # NUGET_SOURCE: https://api.nuget.org
